name: build-cachelib-debian-10
on:
  schedule:
     - cron:  '30 5 * * 2,6'
jobs:
  build-cachelib-debian-10:
    name: "Debian/Buster - Build CacheLib with all dependencies"
    runs-on: ubuntu-latest
    # Docker container image name
    container: "debian:buster-slim"
    steps:
      - name: "System Information"
        run: |
          echo === uname ===
          uname -a
          echo === /etc/os-release ===
          cat /etc/os-release
          echo === df -hl ===
          df -hl
          echo === free -h ===
          free -h
          echo === top ===
          top -b -n1 -1 -Eg || timeout 1 top -b -n1
          echo === env ===
          env
          echo === cc -v ===
          cc -v
          echo === g++ -v ===
          g++ -
          true
      - name: "update packages"
        run: apt-get update
      - name: "upgrade packages"
        run: apt-get -y upgrade
      - name: "install sudo,git"
        run: apt-get install -y sudo git
      - name: "checkout sources"
        uses: actions/checkout@v2
      - name: "build CacheLib using build script"
        run: ./contrib/build.sh -j -v
